"""Render training results (reports/metrics.json) as Markdown."""

from __future__ import annotations

import re
from typing import Any

README_START = "<!-- results:start -->"
README_END = "<!-- results:end -->"


def _pct(v: float) -> str:
    return f"{v * 100:.1f}%"


def _aed(v: float) -> str:
    return f"{v:,.0f}"


def verdict(test: dict[str, dict[str, float]]) -> str:
    """Plain statement of whether the model beats the baseline on each test metric."""
    m, b = test["model"], test["baseline"]
    wins = {
        "median absolute percentage error": m["mdape"] < b["mdape"],
        "share within 10%": m["within_10pct"] > b["within_10pct"],
        "mean absolute error": m["mae_aed"] < b["mae_aed"],
    }
    if all(wins.values()):
        return "The model beats the baseline on all three test metrics."
    if not any(wins.values()):
        return "The model does not beat the baseline on any test metric."
    better = ", ".join(k for k, v in wins.items() if v)
    worse = ", ".join(k for k, v in wins.items() if not v)
    return f"The model beats the baseline on {better}, but not on {worse}."


def headline_table(results: dict[str, Any]) -> str:
    lines = [
        "| Period | Estimator | Rows | MdAPE | Within 10% | MAE (AED) |",
        "|---|---|---:|---:|---:|---:|",
    ]
    for stage, label in (("validation", "Validation"), ("test", "Test")):
        months = results["split"]["valid_months" if stage == "validation" else "test_months"]
        for name in ("model", "baseline"):
            s = results[stage][name]
            est = "LightGBM" if name == "model" else "Community median baseline"
            lines.append(
                f"| {label} ({', '.join(months)}) | {est} | {s['rows']:,} | {_pct(s['mdape'])} | "
                f"{_pct(s['within_10pct'])} | {_aed(s['mae_aed'])} |"
            )
    return "\n".join(lines)


def _segments_table(results: dict[str, Any], dimension: str) -> str:
    rows = [r for r in results["segments"] if r["dimension"] == dimension]
    by_segment: dict[str, dict[str, dict[str, Any]]] = {}
    for r in rows:
        by_segment.setdefault(r["segment"], {})[r["estimator"]] = r
    lines = [
        "| Segment | Rows | Model MdAPE | Baseline MdAPE | Model within 10% | "
        "Baseline within 10% | In 80% range |",
        "|---|---:|---:|---:|---:|---:|---:|",
    ]
    for seg, est in by_segment.items():
        m, b = est["model"], est["baseline"]
        cover = _pct(m["range_coverage"]) if "range_coverage" in m else "n/a"
        lines.append(
            f"| {seg} | {m['rows']:,} | {_pct(m['mdape'])} | {_pct(b['mdape'])} | "
            f"{_pct(m['within_10pct'])} | {_pct(b['within_10pct'])} | {cover} |"
        )
    return "\n".join(lines)


def _agreement(gap: float) -> str:
    who = "LightGBM's built-in TreeSHAP (used by the API) and the `shap` library"
    if gap == 0:
        return f"{who} give identical values on these rows."
    return f"{who} agree to within {gap:.1e} on these rows."


def _data_line(results: dict[str, Any]) -> str:
    data = results.get("data") or {}
    if not data:
        return "Data: not recorded (trained without a download manifest)."
    return (
        f"Data: DLD open data transaction export, sales registered {data.get('period_start')} to "
        f"{data.get('period_end')}, downloaded {data.get('downloaded_on')} (UTC) "
        f"({data.get('raw_rows', 0):,} raw rows in {len(data.get('files', []))} monthly files)."
    )


def metrics_markdown(results: dict[str, Any]) -> str:
    env = results["environment"]
    split = results["split"]
    parts = [
        "# Training and evaluation report",
        "",
        "Generated by `" + results["command"] + "`. Every number below comes from that run.",
        "",
        _data_line(results),
        "",
        f"Environment: Python {env['python']} on {env['platform']}, LightGBM {env['lightgbm']}, "
        f"pandas {env['pandas']}.",
        "",
        "## Headline",
        "",
        headline_table(results),
        "",
        verdict(results["test"]),
        "",
        'MdAPE is the median absolute percentage error. "Within 10%" is the share of estimates '
        "within 10% of the recorded price. MAE is the mean absolute error in dirhams.",
        "",
        "## Split",
        "",
        f"- Train: {', '.join(split['train_months'])} ({split['rows']['train']:,} rows; "
        f"{split['rows']['train_after_trim']:,} after trimming the price-per-sqm tails)",
        f"- Validation: {', '.join(split['valid_months'])} ({split['rows']['valid']:,} rows)",
        f"- Final fit on train + validation: {split['rows']['final_fit']:,} rows",
        f"- Test: {', '.join(split['test_months'])} ({split['rows']['test']:,} rows, not trimmed)",
        "",
        f"Chosen settings: `{results['chosen']['params']['objective']}` loss, "
        f"{results['chosen']['params']['num_leaves']} leaves, "
        f"min {results['chosen']['params']['min_data_in_leaf']} rows per leaf, "
        f"{results['chosen']['num_boost_round']} boosting rounds "
        f"(best of {len(results['search'])} settings on the validation month).",
        "",
    ]
    files = (results.get("data") or {}).get("files") or []
    if files:
        parts += [
            "## Data snapshot",
            "",
            "| File | Rows | Bytes | SHA-256 | Downloaded |",
            "|---|---:|---:|---|---|",
        ]
        for f in files:
            parts.append(
                f"| {f.get('file')} | {int(f.get('rows', 0)):,} | "
                f"{int(f.get('bytes', 0)):,} | `{f.get('sha256')}` | "
                f"{str(f.get('downloaded_at', ''))[:10]} |"
            )
        parts += [
            "",
            "The export can change after download (late registrations), so a later "
            "download of the same months may not match these checksums.",
            "",
        ]
    if results.get("cleaning"):
        parts += [
            "## Cleaning",
            "",
            "| Step | Rule | Rows in | Removed | Rows out |",
            "|---|---|---:|---:|---:|",
        ]
        for s in results["cleaning"]:
            parts.append(
                f"| {s['step']} | {s['rule']} | {s['rows_in']:,} | {s['removed']:,} | "
                f"{s['rows_out']:,} |"
            )
        parts.append("")
    parts += ["## Error analysis on the test month", ""]
    for dimension in ("registration", "price band", "community data", "rooms"):
        parts += [f"### By {dimension}", "", _segments_table(results, dimension), ""]
    interval = results["interval"]
    parts += [
        "## Estimate range",
        "",
        f"The API returns an 80% range built from validation residuals. On the test month "
        f"{_pct(interval['test_coverage'])} of recorded prices fell inside it (80% nominal).",
        "",
    ]
    if "shap" in results:
        shap = results["shap"]
        parts += [
            "## What drives the estimates (SHAP)",
            "",
            f"Mean absolute SHAP value per feature on {shap['rows']:,} test rows. "
            + _agreement(shap["max_abs_gap_shap_vs_lightgbm"]),
            "",
            "| Feature | Mean abs SHAP | Share |",
            "|---|---:|---:|",
            *[
                f"| {r['label']} | {r['mean_abs_shap']:.4f} | {_pct(r['share'])} |"
                for r in shap["importance"]
            ],
            "",
            "![Mean absolute SHAP value per feature](shap_importance.png)",
            "",
        ]
    if "drift" in results:
        d = results["drift"]
        parts += [
            "## Drift: newest month against the training data",
            "",
            f"Evidently `DataDriftPreset`, {d['current_month']} ({d['current_rows']:,} rows) "
            f"against {', '.join(d['reference_months'])} ({d['reference_rows']:,} rows). "
            f"Columns flagged as drifted: {int(d['drifted_count'] or 0)} of {len(d['columns'])}.",
            "",
            "| Column | Test | Value | Threshold | Drift |",
            "|---|---|---:|---:|---|",
            *[
                f"| {c['column']} | {c['method']} | {c['value']:.4f} | {c['threshold']:.2f} | "
                f"{'yes' if c['drifted'] else 'no'} |"
                for c in d["columns"]
            ],
            "",
            "The full HTML report is written to `reports/drift/` (not committed: it embeds "
            "distributions of the source data).",
            "",
        ]
    return "\n".join(parts)


def readme_block(results: dict[str, Any]) -> str:
    return "\n".join(
        [
            README_START,
            _data_line(results),
            "",
            headline_table(results),
            "",
            f"{verdict(results['test'])} The 80% estimate range covered "
            f"{_pct(results['interval']['test_coverage'])} of test prices.",
            "",
            f"Environment: Python {results['environment']['python']}, LightGBM "
            f"{results['environment']['lightgbm']}. Reproduce with `{results['command']}`; "
            "full breakdown in [reports/metrics.md](reports/metrics.md).",
            README_END,
        ]
    )


def model_card_block(results: dict[str, Any]) -> str:
    lines = [
        README_START,
        _data_line(results),
        "",
        headline_table(results),
        "",
        f"{verdict(results['test'])} The 80% estimate range covered "
        f"{_pct(results['interval']['test_coverage'])} of test prices (80% nominal).",
        "",
    ]
    for dimension in ("registration", "price band", "community data"):
        lines += [f"Test month by {dimension}:", "", _segments_table(results, dimension), ""]
    if "drift" in results:
        d = results["drift"]
        drifted = [c["column"] for c in d["columns"] if c["drifted"]]
        lines += [
            f"Drift ({d['current_month']} against the training months): "
            + (f"flagged for {', '.join(drifted)}." if drifted else "no column flagged."),
            "",
        ]
    lines.append(README_END)
    return "\n".join(lines)


def replace_block(text: str, block: str) -> str:
    pattern = re.compile(re.escape(README_START) + r".*?" + re.escape(README_END), re.DOTALL)
    if not pattern.search(text):
        raise ValueError(f"document has no {README_START} ... {README_END} block")
    return pattern.sub(lambda _: block, text)


def update_readme(readme: str, results: dict[str, Any]) -> str:
    return replace_block(readme, readme_block(results))


def update_model_card(card: str, results: dict[str, Any]) -> str:
    return replace_block(card, model_card_block(results))
